export const CHAT_VIEW = 'CHAT_VIEW'
export const CHAT_SEND_MESSAGE = 'CHAT_SEND_MESSAGE'
export const CHAT_LOAD_MESSAGES = 'CHAT_LOAD_MESSAGES'
export const CHAT_RECEIVE_MESSAGE = 'CHAT_RECEIVE_MESSAGE'